AllCops:
  TargetRubyVersion: 2.1

Style/Next:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - jenkins-jobs/*

Metrics/MethodLength:
  Exclude:
    - jenkins-jobs/*

Style/MethodMissing:
  Enabled: false

# We have plenty of system(*%w(....)) which is good to have because
# ['foo', 'mweo', 'asdf'] is cumbersome AF to write.
Lint/UnneededSplatExpansion:
  Enabled: false
