AllCops:
  TargetRubyVersion: 2.1

Style/Next:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - jenkins-jobs/*

Metrics/MethodLength:
  Exclude:
    - jenkins-jobs/*

Style/MethodMissing:
  Enabled: false

# Style suggestion is to use activesupport to be able to indent heredocs. I say
# fuck this suggestion. I am not going to require some stupid gem to be able to
# indent heredocs. Ruby 2.3 will solve this with <<~ heredocs.
Style/IndentHeredoc:
  Enabled: false

# We have plenty of system(*%w(....)) which is good to have because
# ['foo', 'mweo', 'asdf'] is cumbersome AF to write.
Lint/UnneededSplatExpansion:
  Enabled: false
