Style/Next:
  Enabled: false

Style/SpecialGlobalVars:
    Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - jenkins-jobs/*

Metrics/MethodLength:
  Exclude:
    - jenkins-jobs/*
